# Generated by Django 5.0.6 on 2024-06-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorie",
            name="parent",
        ),
        migrations.AddField(
            model_name="product",
            name="genre",
            field=models.CharField(
                choices=[("homme", "HOMME"), ("femme", "FEMME"), ("vide", " ")],
                default="",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.FloatField(default=0.0, verbose_name="Height (cm)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.FloatField(default=0.0, verbose_name="Length (cm)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.FloatField(default=0.0, verbose_name="Weight (kg)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.FloatField(default=0.0, verbose_name="Width (cm)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categorie",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="categorie",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=0.0, verbose_name="Weight (kg)")),
                ("length", models.FloatField(default=0.0, verbose_name="Length (cm)")),
                ("width", models.FloatField(default=0.0, verbose_name="Width (cm)")),
                ("height", models.FloatField(default=0.0, verbose_name="Height (cm)")),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="store.cart",
                        verbose_name="Cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package",
                "verbose_name_plural": "Packages",
            },
        ),
    ]
