# Generated by Django 5.0.6 on 2024-06-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="last_name",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="name",
            field=models.CharField(default=0.0, max_length=120),
            preserve_default=False,
        ),
    ]
